config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :articles
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 6, maximum: 100 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end
  
    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def show
    end
    
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)

    end
    
    def new
        @article = Article.new
    end
    
    def edit
    end 
    
    def update
        if  @article.update(article_params)
            flash[:notice] = "Article updated"
            redirect_to @article
        else
            render 'edit'
        end 
    end 
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article created"
            redirect_to article_path(@article)
        else
            render 'new'
        end 
    end
    
    def destroy
        @article.destroy
        redirect_to articles_path
    end
        
    private
    
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end 
    
    def require_same_user
        if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can't edit or delete this article"
        redirect_to @article
        end
    end
        
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if  @category.update(category_params)
        flash[:notice] = "Category name updated"
        redirect_to @category
    else
        render 'edit'
    end 
  end 
  
  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to articles_path if logged_in?
    end
    
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
    
    def create
         user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @user = User.find(params[:id])
        @articles = @user.articles.paginate(page: params[:page], per_page: 3)
    end
    
    def new
        @user = User.new
    end
    
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end
    
    
    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Account updated"
            redirect_to @user
        else
            render 'edit'
        end
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
            flash[:notice] = "Account created #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end 
    end
    
    def destroy
      @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:notice] = "Account and all associated articles successfully deleted"
      redirect_to articles_path
    end

    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end 
    
    def set_user
      @user = User.find(params[:id])
    end
    
    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only edit your own account"
        redirect_to @user
      end
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
    
    


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
           
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            
            <% if article.categories.any? %>
                <div> <%= render article.categories %> </div>
            <% end %>
            
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div> 

app/views/articles/_forms.html.erb
<div class="container">

<%= render 'shared/errors', obj: @article %>

<%= form_with(model: @article, class:"card shadow pt-4 pr-4 mb-5 bg-secondary rounded", local: true) do |f| %>
    <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label" %> 
        <div class="col-10">
        <%= f.text_field :title, class: "form-control shadow rounded" %>
        </div>
    </div>  

    <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label" %> 
        <div class="col-10">
        <%= f.text_area :description, rows: 5, class: "form-control shadow rounded" %>
        </div>
    </div>  
    
    <div class="form-group row">
        <%= f.label :categories, class: "col-2 col-form-label" %> 
        <div class="col-10">
          <%= f.collection_select(:category_ids, Category.all, :id, :name, 
          { prompt: "(No categories)"}, { multiple: true, size: 5, class: "custom-select shadow rounded" }) %>
        </div>
    </div>  

  <div class="form-group row justify-content-center">
      <%= f.submit class: "btn btn-primary" %>
  </div>


<% end %>

    <div class="row justify-content-center">
        <%= link_to 'Return to all articles', articles_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2">Edit Article</h1>

<%= render 'forms' %>


</div>

app/views/articles/index.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2">Articles listing</h1>

<!--
<div class="apple_pagination">
    <%= will_paginate @article, :container => false %>
  </div>
-->
<%= render 'article' %>

<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @article %>
    </div>
    <%= will_paginate @article, :container => false %>
  </div>
  
</div>

app/views/articles/new.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2">New Article</h1>

<%= render 'forms' %>


</div>

app/views/articles/show.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">

    <h2 class="text-center pt-2"><%= @article.title %></h2>
    
    <div class="container">
            <div class="card shadow  mb-5 bg-white rounded">
              <div class="card-header">
                <h5 class="card-title">
                  by <%= @article.user.username %> 
                  <p></p>
                  <%= link_to gravatar_for(@article.user, size: 100), user_path(@article.user) %>
                  
                  <% if @article.categories.any? %>
                    <%= render @article.categories %>
                  <% end %>
                  
                </h5>
              </div>
              <div class="card-body">
                <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                    <a href=<%= edit_article_path(@article) %> class="btn btn-warning shadow">Edit Article</a>
                    <%= link_to "Delete", article_path(@article), class: "btn btn-danger shadow", method: :delete, data: {confirm: "Are you sure?"} %>
                  <% end %>
                </div>
              <div class ="card-footer"> 
                <p> <small> Added <%= time_ago_in_words(@article.created_at) %> ago </small> -
                <small> Edited <%= time_ago_in_words(@article.updated_at) %> ago </small> </p>
              </div>
            </div>
    </div>


</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mt-3 btn-sm shadow" %> 

app/views/categories/edit.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2">Edit Category</h1>

<div class="container">

<%= render 'shared/errors', obj: @category %>

<%= form_with(model: @category, class:"card shadow pt-4 pr-4 mb-5 bg-secondary rounded", local: true) do |f| %>
    <div class="form-group row">
        <%= f.label :name, class: "col-2 col-form-label" %> 
        <div class="col-10">
        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Category"  %>
        </div>
    </div>  

<div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-primary" %>
</div>


<% end %>

    <div class="row justify-content-center">
        <%= link_to 'Return to categories', categories_path, class: "btn btn-primary" %>
    </div>
</div>

</div>

app/views/categories/index.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


  <h1 class="text-center pt-2">Categories </h1>
  
  <div class="container">
    <% @categories.each do |category| %>
      <div class="row justify-content-md-center">
        <div class="col-5 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            </div>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
            
            <% if current_user.admin? %>
              <div>
              <%= link_to "Edit", edit_category_path(category), class: "btn btn-info mb-2" %>
              </div>
            <% end %>
            
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
              edited <%= time_ago_in_words(category.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div> 

  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @categories %>
    </div>
    <%= will_paginate @categories, :container => false %>
  </div>
  
</div>

app/views/categories/new.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2">New Category</h1>

<div class="container">

<%= render 'shared/errors', obj: @category %>

<%= form_with(model: @category, class:"card shadow pt-4 pr-4 mb-5 bg-secondary rounded", local: true) do |f| %>
    <div class="form-group row">
        <%= f.label :name, class: "col-2 col-form-label" %> 
        <div class="col-10">
        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Category"  %>
        </div>
    </div>  

<div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-primary" %>
</div>


<% end %>

    <div class="row justify-content-center">
        <%= link_to 'Return to all articles', articles_path, class: "btn btn-primary" %>
    </div>
</div>

</div>

app/views/categories/show.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2"> <%= @category.name %> </h1>

<% if current_user.admin? %>
  <div class="row justify-content-center">
  <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-info mb-2 mr-2" %>
  </div>
<% end %>

<div class="container">
  <% @articles.each do |article| %>
    <% if article.categories.ids.include?(@category.id) %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
             
              <% if article.user %>
                by <%= link_to article.user.username, user_path(article.user) %>
              <% end %>
              
              <% if article.categories.any? %>
                  <div> <%= render article.categories %> </div>
              <% end %>
              
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>
              <%= link_to "View", article_path(article), class: "btn btn-success" %>
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-info" %>
                <%= link_to "Delete", article_path(article), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
              edited <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div> 

<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>
  
</div>

app/views/layouts/_messages.html.erb
<div class="container pt-4">
  <% flash.each do |name, msg| %>
   <% if name == "notice" %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
      </button>
        <%= msg %>
   <% else %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
      </button>
        <%= msg %>
   <% end %>

     <% end %>
   </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Test App", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        
        <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link active" %>
        </li>
        
        <li class="nav-item dropdown text-dark">
        <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
          <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link" %>
        </li>
        
        <% if logged_in? %>
          <li class="nav-item">
          <%= link_to 'Create article', new_article_path, class: "nav-link" %>
          </li>
        <% end %>
        </ul>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Categories
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
          <li class="nav-item">
              <%= link_to  "Categories", categories_path, class: "nav-link" %> 
          </li>
          
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to  "Add category", new_category_path, class: "nav-link" %> 
            <% end %>
          </li>
        </ul>
      </li>
      
        
        
         <% if logged_in? %>
           <% if !current_user.admin? %>
            <li class="nav-item">
              <%= link_to  current_user.username, user_path(current_user), class: "nav-link" %> 
            
            <% else %>
              <%= link_to current_user.username + " (admin)", user_path(current_user), class: "nav-link" %>
          <% end %>
          
          
          
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
        
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
        
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
   
    
    <footer id="sticky-footer" class="py-4 bg-dark text-white mt-auto">
      <div class="container text-center">
        <small>
          Made by Nantsi
        </small>
      </div>
    </footer>
     </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'To all articles', articles_path %>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">

<div class="container p-4" id="home-container">
  <div class="jumbotron text-center text-black">
    <h1 class="display-4">Test App</h1>
      <p class="lead">This is my practise blog application.</p>
    <hr class="my-4">
      <p> 
        You can read other people's articles, and if you create an account
        you can also write and edit articles.
      </p>
    <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>




</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h2>There were errors: </h2>
        <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">

<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, class:"card shadow pt-4 pr-4 mb-5 bg-secondary rounded", local: true) do |f| %>
    <div class="form-group row">
        <%= f.label :username, class: "col-2 col-form-label" %> 
        <div class="col-10">
        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username"  %>
        </div>
    </div>  

    <div class="form-group row">
        <%= f.label :email, class: "col-2 col-form-label" %> 
        <div class="col-10">
        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email"  %>
        </div>
    </div>  
    
    <div class="form-group row">
        <%= f.label :password, class: "col-2 col-form-label" %> 
        <div class="col-10">
        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Create a password"  %>
        </div>
    </div>  

<div class="form-group row justify-content-center">
    <%= f.submit "Sign up", class: "btn btn-primary" %>
</div>


<% end %>

    <div class="row justify-content-center">
        <%= link_to 'Return to all articles', articles_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/users/edit.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2">Edit user</h1>

<%= render 'form' %>


</div>

app/views/users/index.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2"> All users </h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
                <%= link_to gravatar_for(user, size: 175), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View", user, class: "btn btn-success" %>
            <% if logged_in?%>
              <% if user == current_user %>
                <%= link_to "Edit", edit_user_path(user), class: "btn btn-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete", user_path(user), class: "btn btn-danger", method: :delete, 
                data: {confirm: "Are you sure"}%>
              <% end %>
            <% end %>
            
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(user.created_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div> 


  <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
  </div>

</div>

app/views/users/new.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2">Sign up</h1>

<%= render 'form' %>


</div>

app/views/users/show.html.erb
<div id="page-content" class="d-flex flex-column min-vh-100">


<h1 class="text-center pt-2"><%= @user.username %> Profile </h1>

<%= gravatar_for @user, size: 200 %>
    
<div class="text-center mt-4">
    <% if logged_in? and @user == current_user || current_user.admin? %>
        <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-info" %>
        <%= link_to "Delete profile", user_path(current_user), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
    <% end %>
</div>

<h3 class="text-center mt-4">Articles</h3>

    <%= render 'articles/article' %>

<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>

</div>